apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-srv
  template:
    metadata:
      labels:
        app: api-srv
    spec:
      containers:
      - name: api-srv
        image: <docker-image> # placeholder for the git action to locate this section and replace it with the ecr image
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 400Mi
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 4000
        #   initialDelaySeconds: 40
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 4000
        #   initialDelaySeconds: 40
        #   periodSeconds: 10
           
---
apiVersion: v1
kind: Service
metadata:
  name: api-srv
spec:
  selector:
    app: api-srv
  ports:
  - port: 4000
    targetPort: 4000
